name: CI/CD Pipeline for Streamlit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            set -e
            echo "===== SERVER CHECK ====="
            hostname
            whoami
            pwd
            curl -s ifconfig.me || true
            echo ""

            echo "===== GIT CHECK BEFORE ====="
            cd /home/ubuntu/YoutubeSummary
            git log -1 --oneline

            echo "===== DEPLOY ====="
            git fetch origin
            git reset --hard origin/main

            echo "===== GIT CHECK AFTER ====="
            git log -1 --oneline

            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart insight-pipeline.service
            sudo systemctl status insight-pipeline.service --no-pager
